spring:

  r2dbc:
    password: thaovtt1234
    url: r2dbc:mysql://localhost:3306/oauth2
    username: root

logging:
  level:
    org:
      springframework:
        security: trace

server:
  port: 9000
