server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/oauth2
    username: root
    password: thaovtt1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          login-client:
            client-id: oidc-client
            client-secret: 'client-secret'
            provider: spring
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login"
            scope: openid
            client-name: login-client
          authorized-client:
            client-id: oidc-client
            client-secret: 'client-secret'
            provider: spring
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login"
            scope: read
            client-name: authorized-client
        provider:
          spring:
            issuer-uri: http://localhost:9000
